ego:
  fastdfs:
    nginx: http://192.168.8.129:8888/
  bigad:
    categoryId: 89
  rabbitmq:
    content:
      queueName: queue
    item:
      insertName: insertitem
  search:
    insert: http://localhost:8083/insert